version: '3'

services:
  bot:
    depends_on:
      - postgres_compass
    build: .
    container_name: work_bot
    restart: always
    command: python main.py
    networks:
      - bot_network
    volumes:
      - /Users/user/Desktop/WorkBot/media:/path/in/container/media

  osor_client_bot:
    build: /Users/user/Desktop/ClientBotOSOR
    container_name: osor_client_bot
    restart: always
    command: python main.py
    networks:
      - bot_network

    volumes:
      - /path/in/container/media/photos:/path/in/container/media/photos


  postgres_compass:
    image: postgres:latest
    container_name: postgres_container_compass
    restart: always
    environment:
      POSTGRES_DB: osor_tg_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - bot_network
    volumes:
      - /Users/user/Desktop/WorkBot/media/photos:/path/in/container/media

networks:
  bot_network:
