version: '3'

services:
  bot:
    depends_on:
      - postgres_compass
    build: .
    container_name: work_bot
    restart: always
    command: python main.py
    networks:
      - bot_network

  postgres_compass:
    image: postgres:latest
    container_name: postgres_container_compass
    restart: always
    environment:
      POSTGRES_DB: osor_tg_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - bot_network


networks:
  bot_network:
