version: '3.9'

services:
  bot:
    container_name: osor_work_bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app/ess-backend
      - ../media:/app/ess-backend/media
    command: "sh /app/osor_work_bot/entrypoints/start_bot.sh"
    env_file:
      - .env
    networks:
      - db_network
      - shared_network

  postgres:
    image: postgres:13.3
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - db_network
      - shared_network
    env_file:
      - .env
    volumes:
      - ../storage:/var/lib/postgresql/data

networks:
  db_network:
    driver: bridge
  shared_network:
    external: true